# Generated by Django 5.2.4 on 2025-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='total_star_count',
            field=models.IntegerField(default=0),
        ),
    ]
