# Generated by Django 5.2.4 on 2025-07-11 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='영화 제목')),
                ('release_year', models.IntegerField(verbose_name='개봉 년도')),
                ('genre', models.CharField(choices=[('SF', 'SF'), ('Comedy', '코미디'), ('Action', '액션'), ('Drama', '드라마'), ('Horror', '공포'), ('Thriller', '스릴러'), ('Fantasy', '판타지'), ('Animation', '애니메이션'), ('Documentary', '다큐멘터리'), ('Romance', '로맨스'), ('Mystery', '미스터리'), ('Crime', '범죄'), ('Adventure', '모험')], max_length=50, verbose_name='장르')),
                ('rating', models.FloatField(help_text='0.0점에서 5.0점 사이로 입력해주세요.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='별점')),
                ('running_time_minutes', models.IntegerField(help_text='단위: 분', verbose_name='러닝타임 (분)')),
                ('review_content', models.TextField(verbose_name='리뷰 내용')),
                ('director', models.CharField(blank=True, max_length=100, null=True, verbose_name='감독')),
                ('actors', models.CharField(blank=True, max_length=200, null=True, verbose_name='주연')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
